In [1]:
import numpy as np

In [2]:
#Task 1
A = np.random.randint(0, 100, 10, dtype=int)
print(arr1)

for i in range(0, 10):
    print(i, A[i])

NameError: name 'arr1' is not defined

In [ ]:
#Task 2
sum = 0
for i in range(0, 10):
    sum+=A[i]
print(f"Sum of the array: {sum}")
print(f"Average value of the array: {sum/len(A)}")

Sum of the array: 459
Average value of the array: 45.9


In [ ]:
#Task 3
min = np.min(A)
max = np.max(A)
print(f"Min value of the array is {min}, at position {np.argmin(A)}")
print(f"Max value of the array is {max}, at position {np.argmax(A)}")

Min value of the array is 7, at position 0
Max value of the array is 73, at position 1


In [ ]:
#Task 4
B = np.sort(A)
C = np.sort(A)[::-1]
print(B)
print(C)

[ 7 12 17 35 48 54 70 71 72 73]
[73 72 71 70 54 48 35 17 12  7]


In [ ]:
#Task 5
n = len(A)
for i in range(n):
    for j in range(0, n-i-1):
        if B[j] > B[j+1]:
            temp = B[j]
            B[j] = B[j+1]
            B[j+1] = temp
print(B)
C = B[::-1]
print(C)

[ 7 12 17 35 48 54 70 71 72 73]
[73 72 71 70 54 48 35 17 12  7]


In [ ]:
#Task 6
 # Print the table
print(f"{'Index'} {'Array A'} {'Array B'} {'Array C'}")
for i in range(len(A)):
    print(f"  {i}      {A[i]}      {B[i]}      {C[i]}")

Index Array A Array B Array C
  0      7      7      73
  1      12      12      72
  2      17      17      71
  3      35      35      70
  4      48      48      54
  5      54      54      48
  6      70      70      35
  7      71      71      17
  8      72      72      12
  9      73      73      7


In [ ]:
#Task 7
D = []
a = 10
for i in range(10):
    D.append(a)
    a+=4
print(D)

[10, 14, 18, 22, 26, 30, 34, 38, 42, 46]


In [6]:
#Task 8
import random

# Generate a random integer between 1 and 10
random_number = random.randint(1, 10)
random_number   # Hide this by scrolling down

while True:
    # Ask the user to guess the number
    guess = int(input("Guess a number between 1 and 10: "))

    # Check if the guess is correct
    if guess < random_number:
        print("Too low!")
    elif guess > random_number:
        print("Too high!")
    else:
        print("Congratulations! You guessed the number.")
        break

Too low!
Congratulations! You guessed the number.
