In [3]:
print("H")

H


In [2]:
import numpy as np

In [57]:
#Task 1
A = np.random.randint(0, 100, 10, dtype=int)
print(arr1)

for i in range(0, 10):
    print(i, A[i])

[93  4 59  3 27 74 44 19 64  5]
0 7
1 73
2 12
3 70
4 17
5 48
6 35
7 72
8 71
9 54


In [58]:
#Task 2
sum = 0
for i in range(0, 10):
    sum+=A[i]
print(f"Sum of the array: {sum}")
print(f"Average value of the array: {sum/len(A)}")

Sum of the array: 459
Average value of the array: 45.9


In [59]:
#Task 3
min = np.min(A)
max = np.max(A)
print(f"Min value of the array is {min}, at position {np.argmin(A)}")
print(f"Max value of the array is {max}, at position {np.argmax(A)}")

Min value of the array is 7, at position 0
Max value of the array is 73, at position 1


In [62]:
#Task 4
B = np.sort(A)
C = np.sort(A)[::-1]
print(B)
print(C)

[ 7 12 17 35 48 54 70 71 72 73]
[73 72 71 70 54 48 35 17 12  7]


In [61]:
#Task 5
n = len(A)
for i in range(n):
    for j in range(0, n-i-1):
        if B[j] > B[j+1]:
            temp = B[j]
            B[j] = B[j+1]
            B[j+1] = temp
print(B)
C = B[::-1]
print(C)

[ 7 12 17 35 48 54 70 71 72 73]
[73 72 71 70 54 48 35 17 12  7]


In [72]:
#Task 6
 # Print the table
print(f"{'Index'} {'Array A'} {'Array B'} {'Array C'}")
for i in range(len(A)):
    print(f"  {i}      {A[i]}      {B[i]}      {C[i]}")

Index Array A Array B Array C
  0      7      7      73
  1      12      12      72
  2      17      17      71
  3      35      35      70
  4      48      48      54
  5      54      54      48
  6      70      70      35
  7      71      71      17
  8      72      72      12
  9      73      73      7


In [79]:
#Task 7
D = []
a = 10
for i in range(10):
    D.append(a)
    a+=4
print(D)

[10, 14, 18, 22, 26, 30, 34, 38, 42, 46]


In [96]:
#Task 8
import random
random_num = random.randint(1, 10)
print(type(random_num))
print(random_num)
n = int(input('Enter a number between 1 and 10: '))
print(type(n))
if n == random_num:
    print('Hay lam djtmemay')
else:
    print('Ngu')

<class 'int'>
10


Enter a number between 1 and 10:  10


<class 'int'>
Hay lam djtmemay
